### ISSUE TITLE
The add-on doesn't work with the newest version of blender (2.93)

### ISSUE THREAD

**Issue by TheFip** [eliemichel/MapsModelsImporter#172] opened 2021-06-04 11:12 UTC
If i use the previous version of Blender to open the .rdc file it opens just fine, but when i tried to open it with the new update it kept giving an error.

**Comment by eliemichel** [comment] 2021-06-07 07:21
Confirmed, there is a change of underlying version of Python with the 2.93, I'll have to rebuild the C++ part of the add-on.

**Comment by mupfelofen-de** [comment] 2021-06-15 11:57
Since I installed Blender using the Windows Store, I can't simply downgrade to an earlier version. I hope this issue will fix soon. Can't wait to give it a try. :-)

**Comment by eliemichel** [comment] 2021-06-24 13:53
Fixed with v0.4.0

**Closed by eliemichel** 2021-06-24 13:53 UTC
