### ISSUE TITLE
Cannot import RDC1.19 file to blender3.1

### ISSUE THREAD

**Issue by Hareden** [eliemichel/MapsModelsImporter#243] opened 2022-10-31 03:35 UTC
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc 
 - 
![image](https://user-images.githubusercontent.com/106158319/198925935-e15a741b-aade-4c13-b4ec-712941e91bac.png)

 - Your GPU name
 - Version of this add-on  0.5.0
 - Version of RenderDoc1.19
 - Version of Blender 3.1
 - 
![image](https://user-images.githubusercontent.com/106158319/198925314-699f7f3f-e8e2-438d-bc21-96feb08a35d0.png)

Before even reporting, make sure that you are using [the last version](https://github.com/eliemichel/MapsModelsImporter/releases/latest) of this add-on and that you stick to the version of Blender and RenderDoc indicated in the release notes of this last version!

**Comment by eliemichel** [comment] 2022-11-06 17:04
Possible duplicate of https://github.com/eliemichel/MapsModelsImporter/issues/238

**Comment by Jinuro** [comment] 2022-12-27 14:38
I don't know why it shows
Invalid RDC capture file. Please make sure that:
1. You are using the recommended RenderDoc Version for this Add-on
   - RenderDoc Version 1.5 - 1.9 for MapsModelsImporter <= 0.3.2
   - RenderDoc Version = 1.10 for MapsModelsImporter >= 0.3.3 and <= 0.3.7
   - RenderDoc Version 1.13 - 1.14 for MapsModelsImporter >= 0.4.0  and <= 0.4.2
   - RenderDoc Version = 1.19 for MapsModelsImporter >= 0.5.0
2. You are importing from Google Maps or Google Earth web
3. You were MOVING in the 3D view while taking the capture (you can use the "Capture after delay"-button in RenderDoc).

Before opening a new Issue on GitHub please download a working sample file to check if this works on your Computer.
Please be patient. If there's no error message it might still be loading. 
It can take a minute or two to load it and Blender will get unresponsive during this time.
Find sample files here: https://github.com/eliemichel/MapsModelsImporter-samples

If it works with a sample file you most probably shouldn't open a new issue on GitHub but figure out how to use RenderDoc.
Find instructions about using RenderDoc by searching YouTube for "Capturing Google Maps with RenderDoc"

If the sample file doesn't work:
Please report to MapsModelsImporter developers providing the full console log with debug information.
First turn on debug output by activating the "Debug Info"-checkbox under Edit > Preferences > Add-ons > MapsModelsImporter
On Windows systems console log is accessible in Windows > Toggle System Console (right click to copy).
On Linux systems you have to run Blender from the console to get the debug output

**Comment by savissimo** [comment] 2022-12-27 14:43
I have the same problem: the error pops up if I use RenderDoc 1.19. 

I tried downloading a sample (Cape Town) created with RenderDoc 1.13 (the most recent one from the samples) and I could import it. I tried capturing with 1.13 and importing my capture, but I got nothing: no error, no mesh imported.

**Comment by Jinuro** [comment] 2022-12-27 15:31
Maybe you can use blender 3.1

**Comment by savissimo** [comment] 2022-12-27 16:06
I managed to make it work with RenderDoc 1.19. Apparently, the secret is to use a delayed capture and to move the camera as RenderDoc is capturing. You'll notice the capture goes up into the hundreds of MBs, and Blender will import it.

**Comment by Jinuro** [comment] 2022-12-27 16:29
let me try
your blender is 3.1 or 3.3

**Comment by savissimo** [comment] 2022-12-27 17:22
Mine is 3.3. @Hareden had 3.1.

**Comment by eliemichel** [comment] 2023-02-02 08:15
Recommended versions in February 2023:
 - Use version [0.6.0](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.6.0) of this add-on
 - Use RenderDoc v1.25
 - Use Blender 3.4

**Closed** 2023-02-02 08:15 UTC
