### ISSUE TITLE
Error importing RDC file in Blender

### ISSUE THREAD

**Issue by walter923** [eliemichel/MapsModelsImporter#84] opened 2020-09-21 04:01 UTC
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 -The .rdc file https://drive.google.com/file/d/16rssDWgZaM_-u8v7kcMFFEJ5RR_TOSgT/view?usp=sharing
 - NVIDIA GTX 1650
 - Version of this add-on (v0.3.1)
 - Version of RenderDoc (1.10)
 - Version of Blender (2.83.6)

I am following Flying Theston's video on importing maps into MSFS.
https://www.youtube.com/watch?feature=youtu.be&v=ZdCP11rqpVk&app=desktop

**Comment by FlyBoyRez** [comment] 2020-09-21 04:39
Hello, I can't import any of the RDC files no matter how carefully I follow the videos or the suggestions in this issues page.

The RDC file is here: https://drive.google.com/file/d/1c_16bJmD4Y2w4ouoaai4x73fcHR4w1sz/view?usp=sharing

- Nvidia RTX2060 Super - Driver version 456.38

- MapsModel Importer V3.1 or 3.2 (no difference)

- RenderDoc V1.10

- Blender V2.83.1 or V2.90 (no difference)

I have followed Flying Theston's guide (https://www.youtube.com/watch?v=ZdCP11rqpVk&list=PL0T8moFeUf7dwAZfo53dXIZQZ-aU5xEXA) and Nicko16's guide (https://www.youtube.com/watch?v=F_XsmoZJmG8)

The error message in each case is:
Invalid RDC capture file. Please make sure that:
1. You are importing from Google Maps (NOT Google Earth)
2. you were MOVING in the 3D view while taking the capture (you can use the Capture after delay button in RenderDoc).

I can confirm I am accessing Google Maps through Google Chrome and that I used a 5 sec delay and was moving the map when the capture took place (the movement briefly stuttered)

The console logs on one occasion recorded this:

Read prefs: C:\Users\Rez\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.83\2.83\python
addon_utils.disable: MapsModelsImporter not loaded
Modules Installed (MapsModelsImporter) from 'C:\\Blender Plugins\\MapsModelsImporter-v0.3.1.zip' into 'C:\\Users\\Rez\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons'
module changed on disk: 'C:\\Users\\Rez\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons\\MapsModelsImporter\\__init__.py' reloading...


However all subsequent console logs only say this:

Read prefs: C:\Users\Rez\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.83\2.83\python

Any guidance would be hugely appreciated!

Rez

**Comment by eliemichel** [comment] 2020-09-21 08:15
Hi @walter923 , as @FlyBoyRez noticed, it is indeed due to RenderDoc, use version 1.9.
(duplicate of #81 #82 and #83)

**Closed by eliemichel** 2020-09-21 08:16 UTC

**Comment by walter923** [comment] 2020-09-21 12:31
@eliemichel will be trying that thank you for the quick reply.
